### ISSUE TITLE
[BUG] [MACOS] edstart completion on MacOs Catalina results in grep error

### ISSUE THREAD

**Issue by dpangier** [matthieusb/zsh-edward#6]
Completion of `edward start` results in the error:

```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

The options `-P`  and `-z` are not supported in the OS bundled version of grep.

Using `pcregrep -M` as an alternative works here. YMMV.

**Comment by matthieusb** [comment]
Hi,

`pcregrep` does not appear to be pre-installed on my personal linux machine, running ubuntu 18.04.
As it does not seem to be standard, I'll try to add MacOS specific behavior to my script.
However, I don't have a MacOS machine to test it, so I'll rely on your feedback.

Feel  free to propose a pull request to help me.

Matt.

**Comment by dpangier** [comment]
Sure, I'll have a tinker - your observation made me check, and I can see that `pcregrep` isn't part of base Catalina either.
